DEFAULT_CONFIG = {
    "epochs": 10,
    "batch_size": 32,
    "learning_rate": 0.001,
    "num_layers": 3,
    "hidden_size": 64,
    "optimizer": "adam",
    "loss": "cross_entropy_loss",
    "activation": "relu",
    "momentum": 0.9,
    "beta": 0.9,
    "beta2": 0.999,
    "epsilon": 1e-8,
    "weight_decay": 0.0,
    "weight_init": "xavier",
}
